# Generated by Django 3.2.13 on 2022-05-09 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20220509_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='name',
            field=models.CharField(default='Unnamed Listing', max_length=64),
        ),
        migrations.AddField(
            model_name='listing',
            name='starting_bid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='desc',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='top_bidder',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='winning', to=settings.AUTH_USER_MODEL),
        ),
    ]
