# Generated by Django 3.2.13 on 2022-05-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20220513_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
